### ISSUE TITLE
Installing node dependencies

### ISSUE THREAD

**Issue by matthiasrsl** [cglusky/docker-django-react#24]
When I try to install npm dependecies in the frontend, I always end up with `Module not found` when running the containers.

I tried rebuilding everything as follows when installing dependencies:
```
docker compose down -v
cd frontend/
npm install react-table
cd ..
docker compose build --no-cache
docker compose up
```
to no avail

I also tried [this StackOverflow solution](https://stackoverflow.com/a/32785014), without success.

What is your workflow to install dependencies on the frontend side ?

Thanks a lot for your help !

**Comment by cglusky** [comment]
@matthiasrsl Sorry it took me so long to reply to this.  Let me have a closer look.

**Comment by cglusky** [comment]
@crhowell Think I should add this to readme?

**Comment by cglusky** [comment]
Workflow for adding npm modules is:

1. Hand edit package.json and rebuild
2. run `docker compose exec -it dev-react /bin/bash` to bring up a shell inside react container and then run `npm install whatever` inside that shell.

The node modules folder is created/mounted inside the react container, and does not have a corresponding node modules on local machine.  This prevents issues with permissions and/or architecture problems.  Which means you can not perform an `npm install whatever` outside the container.

Gonna close this one.  Thanks for interest in the template!
