### ISSUE TITLE
Difference between docker-compose.prod.yml and docker-compose.yml

### ISSUE THREAD

**Issue by ghost** [cglusky/docker-django-react#6]
Hi, looks like you've made a nice peace of work getting a good structure. But what are the thoughs behind the prod configuration not having the same services as dev?

**Comment by cglusky** [comment]
docker-compose.prod.yml is just an old file I moved to the archives folder for possible reference later.  I need to update the repo with lessons learned from couple other projects.  As it is now it is a good base for trying out containerized Django and React on a local machine.  You would need another docker config to deploy to staging or production environment.
